<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UJP16G5" failures="0" tests="2" name="com.opensourse.admin.qa.POM.TC005_Admin_CreateUserDisabled_POM" time="2.797" errors="1" timestamp="07 jul 2021 17:09:02 GMT" skipped="1">
  <testcase classname="com.opensourse.admin.qa.POM.TC005_Admin_CreateUserDisabled_POM" name="TC005_Admin_CreateUserDisabled_POM_Script" time="0.000">
    <skipped/>
  </testcase> <!-- TC005_Admin_CreateUserDisabled_POM_Script -->
  <testcase classname="com.opensourse.admin.qa.POM.TC005_Admin_CreateUserDisabled_POM" name="beforeTest" time="2.797">
    <error message="JSONObject[&quot;TC005_Admin_CreateUserDisabled_POM&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["TC005_Admin_CreateUserDisabled_POM"] not found.
at org.json.JSONObject.get(JSONObject.java:472)
at org.json.JSONObject.getJSONObject(JSONObject.java:637)
at com.opensource.base.SeleniumWrapper.getJSONValue(SeleniumWrapper.java:275)
at com.opensourse.admin.qa.POM.TC005_Admin_CreateUserDisabled_POM.beforeTest(TC005_Admin_CreateUserDisabled_POM.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforeTest -->
</testsuite> <!-- com.opensourse.admin.qa.POM.TC005_Admin_CreateUserDisabled_POM -->
